-- TABLE: "Service"
BEGIN;

CREATE TABLE "Service" (
    "ID" serial PRIMARY KEY,
    "RoomID" INT NOT NULL REFERENCES "Room" ("ID") ON DELETE CASCADE,
    "Description" TEXT NOT NULL,
    "RequestedAt" TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    "Status" VARCHAR(50) DEFAULT 'pending' NOT NULL
) TABLESPACE pg_default;

COMMIT;
