// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"time"
)

type Booking struct {
	ID         int32
	UserID     int32
	RoomID     int32
	StartDate  time.Time
	EndDate    time.Time
	TotalPrice string
	Status     string
	CreatedAt  time.Time
}

type Hotel struct {
	ID        int32
	Name      string
	Address   string
	City      string
	Rating    string
	CreatedAt time.Time
}

type Payment struct {
	ID          int32
	BookingID   int32
	Amount      string
	PaymentDate time.Time
	Status      string
}

type Role struct {
	ID          int32
	RoleName    string
	Description string
}

type Room struct {
	ID          int32
	HotelID     int32
	RoomType    string
	Price       string
	IsAvailable bool
	CreatedAt   time.Time
}

type Service struct {
	ID          int32
	RoomID      int32
	Description string
	RequestedAt time.Time
	Status      string
}

type User struct {
	ID               int32
	LastName         string
	FirstName        string
	UserName         string
	Email            string
	IsHashedPassword string
	IsAdmin          bool
	IsUser           bool
	IsReception      bool
	IsFinance        bool
	IsHouseKeeper    bool
	IsActive         bool
	CreatedAt        time.Time
}

type UserRole struct {
	UserID     int32
	RoleID     int32
	AssignedAt time.Time
}
